// Lunch menu additions - adding before the closing bracket of mockRestaurants array

// UDUPI HOTEL LUNCH (VEG)
{
    id: "udupi-lunch",
        name: "Udupi Hotel",
            image: "https://live.staticflickr.com/65535/50012104981_b3f3cb9018_b.jpg",
                rating: 4.5,
                    description: "Traditional vegetarian lunch meals",
                        deliveryTime: "30-40 min",
                            items: [
                                // SOUTH MEALS
                                {
                                    id: "udupi-lunch-1",
                                    name: "South Indian Meals",
                                    price: 100,
                                    description: "ದಕ್ಷಿಣ ಭಾರತೀಯ ಊಟ",
                                    image: "https://images.unsplash.com/photo-1585937421612-70a19fb6930b?w=400&h=300&fit=crop",
                                    category: "Meals",
                                },
                                {
                                    id: "udupi-lunch-2",
                                    name: "Extra Rice",
                                    price: 40,
                                    description: "ಹೆಚ್ಚುವರಿ ಅಕ್ಕಿ",
                                    image: "https://images.unsplash.com/photo-1585937421612-70a19fb6930b?w=400&h=300&fit=crop",
                                    category: "Meals",
                                },
                                {
                                    id: "udupi-lunch-3",
                                    name: "Extra Curd",
                                    price: 10,
                                    description: "ಹೆಚ್ಚುವರಿ ಮೊಸರು",
                                    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop",
                                    category: "Meals",
                                },
                                // NORTH MEALS
                                {
                                    id: "udupi-lunch-4",
                                    name: "North Indian Meals",
                                    price: 150,
                                    description: "ಉತ್ತರ ಭಾರತೀಯ ಊಟ",
                                    image: "https://images.unsplash.com/photo-1585937421612-70a19fb6930b?w=400&h=300&fit=crop",
                                    category: "Meals",
                                },
                                {
                                    id: "udupi-lunch-5",
                                    name: "Roti Curry",
                                    price: 100,
                                    description: "ರೋಟಿ ಕರೀ",
                                    image: "https://images.unsplash.com/photo-1585937421612-70a19fb6930b?w=400&h=300&fit=crop",
                                    category: "Meals",
                                },
                                {
                                    id: "udupi-lunch-6",
                                    name: "Chenna Bhatura",
                                    price: 100,
                                    description: "ಚೆನ್ನಾ ಭಟೂರಾ",
                                    image: "https://images.unsplash.com/photo-1626074353765-517a65ffe5c5?w=400&h=300&fit=crop",
                                    category: "Meals",
                                },
                                {
                                    id: "udupi-lunch-7",
                                    name: "Extra Curry / Dal (1 Cup)",
                                    price: 20,
                                    description: "ಹೆಚ್ಚುವರಿ ಕರೀ / ದಾಲ್ (1 ಕಪ್)",
                                    image: "https://images.unsplash.com/photo-1585937421612-70a19fb6930b?w=400&h=300&fit=crop",
                                    category: "Meals",
                                },
                                // SWEETS
                                {
                                    id: "udupi-lunch-8",
                                    name: "Jamoon (1)",
                                    price: 30,
                                    description: "ಜಾಮೂನ್ (1)",
                                    image: "https://images.unsplash.com/photo-1634141510639-d691d86f47be?w=400&h=300&fit=crop",
                                    category: "Sweets",
                                },
                                {
                                    id: "udupi-lunch-9",
                                    name: "Carrot Halwa",
                                    price: 30,
                                    description: "ಕ್ಯಾರೆಟ್ ಹಲ್ವಾ",
                                    image: "https://www.whiskaffair.com/wp-content/uploads/2020/10/Carrot-Halwa-2-3.jpg",
                                    category: "Sweets",
                                },
                                {
                                    id: "udupi-lunch-10",
                                    name: "Kashi Halwa",
                                    price: 30,
                                    description: "ಕಾಶಿ ಹಲ್ವಾ",
                                    image: "https://www.whiskaffair.com/wp-content/uploads/2018/10/Ash-Gourd-Halwa-1-3.jpg",
                                    category: "Sweets",
                                },
                                // SOUPS
                                {
                                    id: "udupi-lunch-11",
                                    name: "Cream of Tomato Soup",
                                    price: 90,
                                    description: "ಕ್ರೀಮ್ ಆಫ್ ಟೊಮ್ಯಾಟೋ ಸೂಪ್",
                                    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop",
                                    category: "Soups",
                                },
                                {
                                    id: "udupi-lunch-12",
                                    name: "Sweet Corn Soup",
                                    price: 100,
                                    description: "ಸ್ವೀಟ್ ಕಾರ್ನ್ ಸೂಪ್",
                                    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop",
                                    category: "Soups",
                                },
                                {
                                    id: "udupi-lunch-13",
                                    name: "Cream of Mushroom Soup",
                                    price: 100,
                                    description: "ಕ್ರೀಮ್ ಆಫ್ ಮಶ್ರೂಮ್ ಸೂಪ್",
                                    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop",
                                    category: "Soups",
                                },
                                {
                                    id: "udupi-lunch-14",
                                    name: "Hot and Sour Soup",
                                    price: 110,
                                    description: "ಹಾಟ್ ಅಂಡ್ ಸಾರ್ ಸೂಪ್",
                                    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop",
                                    category: "Soups",
                                },
                                {
                                    id: "udupi-lunch-15",
                                    name: "Veg Clear Soup",
                                    price: 100,
                                    description: "ವೆಜ್ ಕ್ಲಿಯರ್ ಸೂಪ್",
                                    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop",
                                    category: "Soups",
                                },
                                // RAITHA
                                {
                                    id: "udupi-lunch-16",
                                    name: "Aloo Raitha",
                                    price: 80,
                                    description: "ಆಲೂ ರೈತಾ",
                                    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&h=300&fit=crop",
                                    category: "Raitha",
                                },
                                {
                                    id: "udupi-lunch-17",
                                    name: "Punjabi Raitha",
                                    price: 80,
                                    description: "ಪಂಜಾಬಿ ರೈತಾ",
                                    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&h=300&fit=crop",
                                    category: "Raitha",
                                },
                                {
                                    id: "udupi-lunch-18",
                                    name: "Cucumber Raitha",
                                    price: 80,
                                    description: "ಸೌತೆಕಾಯಿ ರೈತಾ",
                                    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&h=300&fit=crop",
                                    category: "Raitha",
                                },
                                {
                                    id: "udupi-lunch-19",
                                    name: "Bo ondi Raitha",
                                    price: 100,
                                    description: "ಬೂಂದಿ ರೈತಾ",
                                    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&h=300&fit=crop",
                                    category: "Raitha",
                                },
                                // SALAD
                                {
                                    id: "udupi-lunch-20",
                                    name: "Green Salad",
                                    price: 100,
                                    description: "ಗ್ರೀನ್ ಸಲಾಡ್",
                                    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
                                    category: "Salad",
                                },
                                {
                                    id: "udupi-lunch-21",
                                    name: "Onion Salad",
                                    price: 70,
                                    description: "ಈರುಳ್ಳಿ ಸಲಾಡ್",
                                    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
                                    category: "Salad",
                                },
                            ],
  },
